version: '3.7'

volumes:
  laravel-curriculum-database:
    external: true

networks:
  laravel-curriculum-network:
    external: true

services:
  laravel-curriculum:
    image: ambientum/php:7.4-nginx
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - laravel-curriculum-network

  laravel-curriculum-database:
    image: mysql:5.7
    volumes:
      - laravel-curriculum-database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-curriculum-network
